import './styles.css';
import('./cloud.js');
const founder = 'Israt Jahan Ethina';
const email = 'ij8283707@gmail.com';
const phone = '+8801779923680';
const money = new Intl.NumberFormat('en-BD', { maximumFractionDigits: 0 });

const app = document.querySelector('#app');
app.innerHTML = `
  <div class="app-shell">
    <aside class="sidebar">
      <a class="brand" href="#top" aria-label="Quick Capital home"><span class="brand-mark"><span></span><i></i></span><span>quick<span>capital</span></span></a>
      <div class="workspace-label">WORKSPACE</div>
      <nav class="side-nav">
        <a class="nav-link active" href="#overview"><span class="nav-icon">⌂</span> Overview</a>
        <a class="nav-link" href="#applications"><span class="nav-icon">▤</span> Applications <b>3</b></a>
        <a class="nav-link" href="#calculator"><span class="nav-icon">⌁</span> Calculator</a>
        <a class="nav-link" href="#how-it-works"><span class="nav-icon">⊙</span> How it works</a>
      </nav>
      <div class="sidebar-spacer"></div>
      <div class="support-card"><span class="eyebrow">NEED A HAND?</span><strong>Talk to our team</strong><p>We're here to help your business move forward.</p><a href="mailto:${email}">Contact support <span>↗</span></a></div>
      <div class="side-footer"><div class="user-avatar">IE</div><div><strong>${founder}</strong><small>Founder & owner</small></div><button class="icon-btn" aria-label="More options">•••</button></div>
    </aside>
    <main class="main-content" id="top">
      <header class="topbar"><div class="mobile-brand brand"><span class="brand-mark"><span></span><i></i></span><span>quick<span>capital</span></span></div><div class="breadcrumb"><span>Workspace</span><span>/</span><strong>Overview</strong></div><div class="top-actions"><button class="icon-btn" aria-label="Notifications">♧<em></em></button><button class="profile-pill"><span class="user-avatar small">IE</span><span>${founder}</span><span>⌄</span></button></div><button class="menu-btn" aria-label="Open menu">☰</button></header>
      <div class="page-wrap">
        <section class="hero" id="overview"><div class="hero-copy"><div class="eyebrow accent">BUSINESS FUNDING, MADE CLEAR</div><h1>Capital for your<br/><em>next chapter.</em></h1><p>Quick, transparent funding that helps ambitious businesses grow with confidence.</p><div class="hero-actions"><a class="button primary" href="#applications">Start an application <span>↗</span></a><a class="text-link" href="#how-it-works">See how it works <span>→</span></a></div></div><div class="hero-art"><div class="ring ring-one"></div><div class="ring ring-two"></div><div class="art-card card-back"><span>AVAILABLE TO YOU</span><strong>৳250,000</strong><small>Flexible capital, on your terms</small></div><div class="art-card card-front"><span>YOUR CAPITAL IS</span><strong>WORKING <i>↗</i></strong><div class="chart"><i></i><i></i><i></i><i></i><i></i><i></i><i></i></div><small>+18.4% <b>this quarter</b></small></div></div></section>
        <section class="stats-row"><div><span class="stat-icon">◌</span><p>Application status</p><strong>Ready to apply</strong></div><div><span class="stat-icon">◷</span><p>Average decision</p><strong>24–48 hours</strong></div><div><span class="stat-icon">↗</span><p>Funded to date</p><strong>৳48.6M <small>and growing</small></strong></div><div class="trust"><span>✦</span><p>Built for founders who<br/><strong>think bigger.</strong></p></div></section>
        <section class="section intro-section"><div class="section-heading"><div><span class="eyebrow">WHY QUICK CAPITAL</span><h2>More than funding.<br/><em>A better way forward.</em></h2></div><p>We make business funding feel less like paperwork and more like progress. No hidden terms. No dead ends. Just a clear path to your next milestone.</p></div><div class="feature-grid"><article class="feature-card featured"><span class="feature-number">01</span><span class="feature-icon">⌁</span><h3>Move at your speed</h3><p>Skip the long waits. Get a clear decision in as little as 24 hours.</p><a href="#how-it-works">Explore the process <span>↗</span></a></article><article class="feature-card"><span class="feature-number">02</span><span class="feature-icon">◇</span><h3>Know what to expect</h3><p>Simple terms and real-time updates keep you in control at every step.</p><a href="#calculator">Run the numbers <span>↗</span></a></article><article class="feature-card"><span class="feature-number">03</span><span class="feature-icon">◎</span><h3>Built around you</h3><p>Flexible funding designed around your business, not the other way around.</p><a href="mailto:${email}">Talk to a specialist <span>↗</span></a></article></div></section>
        <section class="split-section" id="how-it-works"><div class="process-copy"><span class="eyebrow">HOW IT WORKS</span><h2>From idea to<br/><em>in motion.</em></h2><p>Five straightforward steps. One clear path to the capital your business needs.</p><a class="text-link" href="#applications">Begin your journey <span>→</span></a></div><div class="steps"><div class="step active"><span>01</span><div><strong>Tell us about your business</strong><p>A few details help us understand where you're headed.</p></div><b>−</b></div><div class="step"><span>02</span><div><strong>Choose your funding</strong></div><b>+</b></div><div class="step"><span>03</span><div><strong>Get a clear decision</strong></div><b>+</b></div><div class="step"><span>04</span><div><strong>Review your offer</strong></div><b>+</b></div><div class="step"><span>05</span><div><strong>Put your capital to work</strong></div><b>+</b></div></div></section>
        <section class="calculator-section" id="calculator"><div class="calculator-copy"><span class="eyebrow">FUNDING CALCULATOR</span><h2>See what’s<br/><em>possible.</em></h2><p>Get a quick estimate of your repayments before you apply. No commitment, no surprises.</p><div class="calculator-note"><span>✦</span><p>Estimates are indicative only. Your final rate depends on your application and business profile.</p></div></div><div class="calculator-card"><div class="calc-field"><label>How much do you need?</label><div class="input-wrap"><span>৳</span><input id="amount" type="number" value="50000" min="1000" step="1000"/><span>BDT</span></div></div><div class="calc-field"><label>Repayment period</label><div class="periods"><button class="period" data-months="6">6 mo</button><button class="period active" data-months="12">12 mo</button><button class="period" data-months="24">24 mo</button><button class="period" data-months="36">36 mo</button></div></div><div class="calc-result"><span>ESTIMATED MONTHLY PAYMENT</span><strong id="monthly">৳4,583</strong><div><span>Total repayment</span><b id="total">৳55,000</b></div><div><span>Estimated rate</span><b>10.0% fixed</b></div></div><a class="button primary full" href="#applications">Apply with this estimate <span>↗</span></a></div></section>
        <section class="questionnaire-section" id="questionnaire">
          <div class="section-heading"><div><span class="eyebrow">QUICK ELIGIBILITY CHECK</span><h2>A clearer path<br/><em>starts here.</em></h2></div><p>Share a few details about your business so we can understand your funding needs and point you in the right direction.</p></div>
          <form class="questionnaire-card" id="questionnaire-form"><div class="questionnaire-head"><div><span class="eyebrow">STEP 1 OF 1</span><h3>Tell us about your business</h3></div><span class="questionnaire-lock">Private &amp; secure</span></div>
          <div class="questionnaire-grid">
            <label>Business foundation year<input name="foundationYear" type="number" min="1900" max="2026" placeholder="e.g. 2018" required /></label>
            <label>Loan amount needed<div class="questionnaire-input"><span>৳</span><input name="loanAmount" type="number" min="1000" step="1000" placeholder="50,000" required /><span>BDT</span></div></label>
            <label>Monthly gross revenue<div class="questionnaire-input"><span>৳</span><input name="monthlyGross" type="number" min="0" step="1000" placeholder="25,000" required /><span>BDT</span></div></label>
            <label>Current credit score<select name="creditScore" required><option value="">Select range</option><option>Excellent (750+)</option><option>Good (700–749)</option><option>Fair (650–699)</option><option>Building (below 650)</option><option>Not sure</option></select></label>
            <label>Any defaults in the last 24 months?<select name="defaults" required><option value="">Select one</option><option>No defaults</option><option>Yes, resolved</option><option>Yes, currently active</option></select></label>
            <label>Current outstanding loans?<select name="loans" required><option value="">Select one</option><option>No outstanding loans</option><option>Yes, under ৳25,000</option><option>Yes, ৳25,000–৳100,000</option><option>Yes, over ৳100,000</option></select></label>
          </div><div class="questionnaire-footer"><p><span>✦</span> No hard credit pull at this stage.</p><button class="button primary" type="submit">Review my answers <span>↗</span></button></div><div class="questionnaire-success" id="questionnaire-success" role="status" aria-live="polite"><strong>Thanks — your details are ready to review.</strong><span>Our funding team can follow up with next steps.</span></div></form>
        </section>
        <section class="applications-section" id="applications"><div class="section-heading"><div><span class="eyebrow">YOUR PORTAL</span><h2>Ready when<br/><em>you are.</em></h2></div><p>Start an application, keep an eye on progress, or connect with our funding team.</p></div><div class="portal-tabs"><button class="portal-tab active" data-portal="owner">Business owner <span>↗</span></button><button class="portal-tab" data-portal="officer">Funding officer <span>↗</span></button><button class="portal-tab" data-portal="admin">Super admin <span>↗</span></button></div><div class="portal-panel" id="portal-panel"></div></section>
        <footer><div class="brand"><span class="brand-mark"><span></span><i></i></span><span>quick<span>capital</span></span></div><p>© 2026 Quick Capital. Funding the businesses shaping tomorrow.</p><div><a href="mailto:${email}">${email}</a><a href="https://wa.me/8801779923680" target="_blank">WhatsApp us</a></div></footer>
      </div>
    </main>
  </div>`;

const panel = document.querySelector('#portal-panel');
const portals = {
  owner: `<div class="portal-top"><div><span class="eyebrow">GOOD MORNING, ${founder.split(' ')[0].toUpperCase()}</span><h3>Your funding journey</h3><p>Pick up where you left off or start something new.</p></div><a class="button primary" href="mailto:${email}?subject=Quick Capital funding application">New application <span>↗</span></a></div><div class="application-card"><div class="application-status"><span class="status-dot"></span><span>APPLICATION IN PROGRESS</span><b>65%</b></div><h4>Growth capital application</h4><p>Last updated today, 10:42 AM</p><div class="progress"><i></i></div><div class="application-meta"><span><small>REQUESTED</small><strong>৳50,000</strong></span><span><small>STATUS</small><strong class="green">Documents needed</strong></span><a href="mailto:${email}">Continue application <span>→</span></a></div></div>`,
  officer: `<div class="portal-top"><div><span class="eyebrow">FUNDING OFFICER VIEW</span><h3>Applications queue</h3><p>Review, verify, and move businesses forward.</p></div><div class="mini-stat"><strong>12</strong><span>pending review</span></div></div><div class="table-card"><div class="table-head"><span>APPLICANT</span><span>REQUEST</span><span>STATUS</span><span></span></div><div class="table-row"><strong>Northstar Studio</strong><span>৳75,000</span><em class="tag amber">Reviewing</em><button class="row-action">Review →</button></div><div class="table-row"><strong>Bloom & Co.</strong><span>৳35,000</span><em class="tag blue">New</em><button class="row-action">Review →</button></div><div class="table-row"><strong>Riverside Goods</strong><span>৳120,000</span><em class="tag green-tag">Verified</em><button class="row-action">Review →</button></div></div>`,
  admin: `<div class="portal-top"><div><span class="eyebrow">SUPER ADMIN VIEW</span><h3>Platform at a glance</h3><p>The vital signs of a healthier funding ecosystem.</p></div><div class="mini-stat"><strong>98.2%</strong><span>platform uptime</span></div></div><div class="admin-grid"><div><span>TOTAL FUNDED</span><strong>৳48.6M</strong><small>↑ 18.4% this year</small></div><div><span>ACTIVE BUSINESSES</span><strong>2,841</strong><small>↑ 12.8% this month</small></div><div><span>AVG. DECISION TIME</span><strong>31h</strong><small>↓ 6h vs last month</small></div></div>`
};
panel.innerHTML = portals.owner;

document.querySelectorAll('.portal-tab').forEach(tab => tab.addEventListener('click', () => { document.querySelectorAll('.portal-tab').forEach(t => t.classList.remove('active')); tab.classList.add('active'); panel.innerHTML = portals[tab.dataset.portal]; }));
document.querySelectorAll('.step').forEach(step => step.addEventListener('click', () => { document.querySelectorAll('.step').forEach(s => s.classList.remove('active')); step.classList.add('active'); const control = step.querySelector('b'); control.textContent = '−'; document.querySelectorAll('.step:not(.active) b').forEach(b => b.textContent = '+'); }));
let months = 12;
function calculate() { const amount = Number(document.querySelector('#amount').value || 0); const total = amount * (1 + 0.10 * months / 12); document.querySelector('#monthly').textContent = '৳' + money.format(Math.round(total / months)); document.querySelector('#total').textContent = '৳' + money.format(Math.round(total)); }
document.querySelector('#amount').addEventListener('input', calculate); document.querySelectorAll('.period').forEach(btn => btn.addEventListener('click', () => { document.querySelectorAll('.period').forEach(b => b.classList.remove('active')); btn.classList.add('active'); months = Number(btn.dataset.months); calculate(); }));
document.querySelector('#questionnaire-form').addEventListener('submit', (event) => { event.preventDefault(); document.querySelector('#questionnaire-success').classList.add('show'); event.currentTarget.querySelector('button').textContent = 'Answers saved ✓'; });
document.querySelector('.menu-btn').addEventListener('click', () => document.querySelector('.sidebar').classList.toggle('open'));
document.querySelectorAll('.nav-link').forEach(link => link.addEventListener('click', () => document.querySelector('.sidebar').classList.remove('open')));
